### PR TITLE
Vitaly's NetHack envs from hackrl

### PR DESCRIPTION
**Pull request by samvelyan**

### CODE REVIEW

**Comment by yobibyte** [comment]
Hey @samvelyan , that's great, thank you! 

Can you do two things before we merge?

- Install pre-commit to keep black happy not to have troubles when we merge back to the original repo.
- Test that the code does not crash when running ```python3 -m nle.scripts.play --env NetHackInventoryManagement-v0```

For example, FULL_ACTIONS is currently undefined in tasks.py. The same is with NLE_SPACE_ITEMS.

**Review by yobibyte — CHANGES_REQUESTED** [review]
Hey @samvelyan , that's great, thank you!

Can you do two things before we merge?

    Install pre-commit to keep black happy not to have troubles when we merge back to the original repo.
    Test that the code does not crash when running python3 -m nle.scripts.play --env NetHackInventoryManagement-v0

For example, FULL_ACTIONS is currently undefined in tasks.py. The same is with NLE_SPACE_ITEMS.

**Comment by samvelyan** [comment]
Thanks @yobibyte. All done.

**Review by yobibyte — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
